window.combinedStations = {
    'Zürich HB': ['Zürich HB', 'Zürich, Sihlquai/HB', 'Zürich, Bahnhofstrasse/HB', 'Zürich, Bahnhofplatz/HB', 'Zürich, Bahnhofquai/HB'],
    'Zürich, Sihlquai/HB': ['Zürich HB', 'Zürich, Sihlquai/HB'],
    'Zürich, Bahnhofquai/HB': ['Zürich HB', 'Zürich, Bahnhofquai/HB'],
    'Zürich, Bahnhofstrasse/HB': ['Zürich HB', 'Zürich, Bahnhofstrasse/HB'],
    'Zürich, Bahnhofplatz/HB': ['Zürich HB', 'Zürich, Bahnhofplatz/HB'],
    'Zürich, Sihlpost/HB': ['Zürich HB', 'Zürich, Sihlpost/HB'],
	'Chur, Post I/Bahnhof': ['Chur', 'Chur, Post I/Bahnhof'],
    'Basel SBB': ['Basel SBB', 'Basel, Bahnhof SBB', 'Basel, Bhfeingang Gundeldingen'],
    'Basel, Bahnhof SBB': ['Basel SBB', 'Basel, Bahnhof SBB'],
    'Basel, Bhfeingang Gundeldingen': ['Basel SBB', 'Basel, Bhfeingang Gundeldingen'],
	'Basel Bad Bf': ['Basel Bad Bf', 'Basel, Badischer Bahnhof'],
	'Basel, Badischer Bahnhof': ['Basel Bad Bf', 'Basel, Badischer Bahnhof'],
	'Aeschi SO, Bolkenstrasse': ['Aeschi SO, Bolkenstrasse', 'Aeschi SO, Kirche'],
	'Aeschi SO, Kirche': ['Aeschi SO, Bolkenstrasse', 'Aeschi SO, Kirche'],
    'Locarno': ['Locarno', 'Locarno FART', 'Locarno, Stazione', 'Locarno, Piazza Stazione'],
    'Locarno, Stazione': ['Locarno', 'Locarno FART', 'Locarno, Stazione', 'Locarno, Piazza Stazione'],
    'Locarno FART': ['Locarno', 'Locarno FART', 'Locarno, Stazione', 'Locarno, Piazza Stazione'],
    'Locarno, Piazza Stazione': ['Locarno', 'Locarno FART', 'Locarno, Stazione', 'Locarno, Piazza Stazione'],
	'Delémont, gare CFF sud': ['Delémont, gare CFF sud', 'Delémont'],
	'Innertkirchen Grimseltor': ['Innertkirchen Grimseltor', 'Innertkirchen, Grimseltor'],
    'Brienz': ['Brienz', 'Brienz BE, Bahnhof'],
    'Brienz BE, Bahnhof': ['Brienz', 'Brienz BE, Bahnhof'],
    'Muttenz': ['Muttenz', 'Muttenz, Bahnhof'],
    'Sursee, Bahnhof': ['Sursee', 'Sursee, Bahnhof', 'Sursee, Schnydermatt'],
	'Sursee': ['Sursee', 'Sursee, Schnydermatt', 'Sursee, Bahnhof'],
	'Sursee, Schnydermatt': ['Sursee', 'Sursee, Schnydermatt', 'Sursee, Bahnhof'],
	'Strengelbach, Gemeindehaus': ['Strengelbach, Gemeindhaus', 'Strengelbach, Kreuzplatz'],
	'Strengelbach, Kreuzplatz': ['Strengelbach, Gemeindhaus', 'Strengelbach, Kreuzplatz'],
	'Küngoldingen': ['Küngoldingen', 'Küngoldingen, Post'],
	'Küngoldingen, Post': ['Küngoldingen', 'Küngoldingen, Post'],
	'Oberentfelden': ['Oberentfelden', 'Oberentfelden, Engelplatz'],
	'Oberentfelden, Engelplatz': ['Oberentfelden', 'Oberentfelden, Engelplatz'],
    'Castione-Arbedo': ['Castione-Arbedo', 'Castione, Stazione'],
    'Castione, Stazione': ['Castione-Arbedo', 'Castione, Stazione'],
    'Horgen': ['Horgen', 'Horgen (See)'],
    'Meilen': ['Meilen', 'Meilen Autoquai'],
    'Zürich, Bürkliplatz': ['Zürich Bürkliplatz (See)', 'Zürich, Bürkliplatz'],
	'Bigenthal': ['Bigenthal', 'Bigenthal, Dorfstrasse'],
	'Bigenthal, Dorfstrasse': ['Bigenthal', 'Bigenthal, Dorfstrasse'],
	'Schafhausen i.E., Thunstrasse': ['Schafhausen i.E., Thunstrasse', 'Schafhausen i.E.'],
	'Schafhausen i.E.': ['Schafhausen i.E., Thunstrasse', 'Schafhausen i.E.'],
    'Oberburg': ['Oberburg, Geissrütti', 'Oberburg'],
    'Oberburg, Geissrütti': ['Oberburg, Geissrütti', 'Oberburg'],
    'Luzern': ['Luzern', 'Luzern Bahnhofquai', 'Luzern, Bahnhof', 'Luzern, Inseliquai/Bahnhof'],
    'Luzern Bahnhofquai': ['Luzern', 'Luzern Bahnhofquai'],
    'Kastanienbaum, Schiffstation': ['Kastanienbaum, Schiffstation', 'Kastanienbaum (See)'],
    'Dornach-Arlesheim': ['Dornach, Bahnhof', 'Dornach-Arlesheim'],
    'Dornach, Bahnhof': ['Dornach, Bahnhof', 'Dornach-Arlesheim'],
    'Basel Dreispitz': ['Basel, Dreispitz', 'Basel Dreispitz'],
	'Basel, Dreispitz': ['Basel, Dreispitz', 'Basel Dreispitz'],
    'Luzern Verkehrshaus': ['Verkehrshaus-Lido', 'Luzern Verkehrshaus', 'Luzern, Verkehrshaus/Lido', 'Luzern, Brüelstrasse'],
    'Verkehrshaus-Lido': ['Verkehrshaus-Lido', 'Luzern, Verkehrshaus/Lido', 'Luzern Verkehrshaus', 'Luzern, Brüelstrasse'],
    'Luzern, Verkehrshaus/Lido': ['Verkehrshaus-Lido', 'Luzern, Verkehrshaus/Lido', 'Luzern Verkehrshaus'],
	'Kriens Mattenhof': ['Kriens, Sternmatt', 'Kriens Mattenhof', 'Kriens, Mattenhof'],
	'Kriens, Mattenhof': ['Kriens, Sternmatt', 'Kriens Mattenhof', 'Kriens, Mattenhof'],
	'Langenthal, Industrie Nord': ['Langenthal Industrie Nord', 'Langenthal, Industrie Nord'],
	'Langenthal Industrie Nord': ['Langenthal Industrie Nord', 'Langenthal, Industrie Nord'],
	'Langenthal Gaswerk': ['Langenthal Gaswerk', 'Langenthal, Gaswerkstrasse'],
	'Langenthal, Gaswerkstrasse': ['Langenthal Gaswerk', 'Langenthal, Gaswerkstrasse'],
    'Langenthal, Bleichestrasse': ['Langenthal, Bleichestrasse', 'Langenthal, Mittelstrasse'],
    'Langenthal, Mittelstrasse': ['Langenthal, Bleichestrasse', 'Langenthal, Mittelstrasse'],
    'Langenthal Süd': ['Langenthal Süd', 'Langenthal Süd, Bahnhof', 'Langenthal, Ringstrasse'],
    'Langenthal Süd, Bahnhof': ['Langenthal Süd', 'Langenthal Süd, Bahnhof', 'Langenthal, Ringstrasse'],
	'Gutenburg': ['Gutenburg', 'Gutenburg, Badstrasse'],
	'Gutenburg, Badstrasse': ['Gutenburg', 'Gutenburg, Badstrasse'],
	'Kleindietwil, Hauptstrasse': ['Kleindietwil, Hauptstrasse', 'Kleindietwil', 'Kleindietwil, Post'],
	'Kleindietwil': ['Kleindietwil, Hauptstrasse', 'Kleindietwil', 'Kleindietwil, Post'],
	'Kleindietwil, Post': ['Kleindietwil, Hauptstrasse', 'Kleindietwil', 'Kleindietwil, Post'],
	'Rohrbach, Hauptstrasse': ['Rohrbach, Hauptstrasse', 'Rohrbach'],
	'Rohrbach': ['Rohrbach, Hauptstrasse', 'Rohrbach'],
	'Dürrenroth, Dorf': ['Dürrenroth, Dorf', 'Dürrenroth'],
	'Dürrenroth': ['Dürrenroth, Dorf', 'Dürrenroth'],
	'Häusernmoos': ['Häusernmoos', 'Häusernmoos, Dorf'],
	'Häusernmoos, Dorf': ['Häusernmoos', 'Häusernmoos, Dorf'],
    'Hasliberg Reuti, Gondelbahn': ['Hasliberg Reuti, Gondelbahn', 'Hasliberg Reuti (Gondelbahn)'],
    'Hasliberg Reuti (Gondelbahn)': ['Hasliberg Reuti, Gondelbahn', 'Hasliberg Reuti (Gondelbahn)'],
    'Meiringen (Luftseilbahn)': ['Meiringen (Luftseilbahn)', 'Meiringen, Luftseilbahn'],
    'Meiringen, Luftseilbahn': ['Meiringen (Luftseilbahn)', 'Meiringen, Luftseilbahn'],
    'Wabern (Gurtenbahn)': ['Wabern bei Bern', 'Wabern (Gurtenbahn)', 'Wabern, Gurtenbahn'],
	'Wabern, Gurtenbahn': ['Wabern bei Bern', 'Wabern (Gurtenbahn)', 'Wabern, Gurtenbahn'],
	'Wabern bei Bern': ['Wabern bei Bern', 'Wabern (Gurtenbahn)', 'Wabern, Gurtenbahn'],
	'Köniz, Schloss': ['Köniz, Schloss', 'Köniz, Weiermatt'],
	'Köniz, Weiermatt': ['Köniz, Schloss', 'Köniz, Weiermatt'],
	'Bern, Fellerstrasse': ['Bern, Fellerstrasse', 'Bern Bümpliz Nord', 'Bern Bümpliz Nord, Bahnhof'],
	'Bern Bümpliz Nord': ['Bern, Fellerstrasse', 'Bern Bümpliz Nord', 'Bern Bümpliz Nord, Bahnhof'],
	'Bern Bümpliz Nord, Bahnhof': ['Bern, Fellerstrasse', 'Bern Bümpliz Nord', 'Bern Bümpliz Nord, Bahnhof'],
	'Liebefeld': ['Liebefeld', 'Liebefeld, Liebefeld Park'],
	'Liebefeld, Liebefeld Park': ['Liebefeld', 'Liebefeld, Liebefeld Park'],
	'Ins [Gleis 11]': ['Ins', 'Ins, Bahnhof'],
	'Oberdorf SO': ['Oberdorf SO', 'Oberdorf SO, Endhalt'],
	'Oberdorf SO, Endhalt': ['Oberdorf SO', 'Oberdorf SO, Endhalt'],
	'Schlieren, Heimeliweg': ['Urdorf', 'Schlieren, Heimeliweg'],
	'Urdorf': ['Urdorf', 'Schlieren, Heimeliweg'],
	'Killwangen, Bahnhof': ['Killwangen, Bahnhof', 'Killwangen-Spreitenbach', 'Killwangen, Bahnhof Nord'],
	'Killwangen, Bahnhof Nord': ['Killwangen, Bahnhof', 'Killwangen-Spreitenbach', 'Killwangen, Bahnhof Nord'],
	'Killwangen-Spreitenbach': ['Killwangen, Bahnhof', 'Killwangen-Spreitenbach', 'Killwangen, Bahnhof Nord'],
	'Unterengstringen, Sennenbüel': ['Unterengstringen, Sennenbüel', 'Unterengstringen, Sennenbüel N'],
	'Unterengstringen, Sennenbüel N': ['Unterengstringen, Sennenbüel', 'Unterengstringen, Sennenbüel N'],
	'Zürich, Allmendstr./Bhf Manegg': ['Zürich Manegg', 'Zürich, Allmendstr./Bhf Manegg'],
	'Zürich Manegg': ['Zürich Manegg', 'Zürich, Manegg', 'Zürich, Allmendstr./Bhf Manegg'],
	'Zürich, Manegg': ['Zürich Manegg', 'Zürich, Manegg'],
	'Sihlau': ['Sihlau', 'Adliswil, Sihlau'],
	'Adliswil, Sihlau': ['Sihlau', 'Adliswil, Sihlau'],
	'Wildpark-Höfli': ['Wildpark-Höfli', 'Langnau am Albis, Zelg'],
	'Langnau am Albis, Zelg': ['Wildpark-Höfli', 'Langnau am Albis, Zelg'],
	'Zürich, Pass. Sihlquai': ['Zürich HB', 'Zürich, Sihlquai/HB'],
	'Zürich, Saalsporthalle': ['Zürich, Saalsporthalle', 'Zürich Saalsporthalle'],
	'Zürich Saalsporthalle': ['Zürich, Saalsporthalle', 'Zürich Saalsporthalle', 'Zürich, Sihlcity'],
	'Zürich, Sihlcity': ['Zürich, Sihlcity', 'Zürich Saalsporthalle'],
	'Zürich Friesenberg': ['Zürich Friesenberg', 'Zürich, Friesenberg'],
	'Zürich, Friesenberg': ['Zürich Friesenberg', 'Zürich, Friesenberg'],
	'Zürich Triemli': ['Zürich Triemli', 'Zürich, Triemlispital'],
	'Zürich, Triemlispital': ['Zürich Triemli', 'Zürich, Triemlispital'],
	'Zürich Enge': ['Zürich Enge, Bahnhof/Bederstr.', 'Zürich Enge, Bahnhof', 'Zürich Enge'],
	'Zürich Enge, Bahnhof/Bederstr.': ['Zürich Enge, Bahnhof/Bederstr.', 'Zürich Enge, Bahnhof', 'Zürich Enge'],
	'Langenthal Industrie Nord': ['Langenthal Industrie Nord', 'Langenthal, Industrie Nord'],
	'Langenthal, Industrie Nord': ['Langenthal Industrie Nord', 'Langenthal, Industrie Nord'],
	'Langenthal Gaswerk': ['Langenthal Gaswerk', 'Langenthal, Gaswerkstrasse'],
	'Langenthal, Gaswerkstrasse': ['Langenthal Gaswerk', 'Langenthal, Gaswerkstrasse'],
	'St-Louis, Gare': ['8718213', 'St-Louis, Gare de Saint-Louis', 'St-Louis, Gare'], //STL
	'8718213': ['8718213', 'St-Louis, Gare de Saint-Louis', 'St-Louis, Gare'], //STL
	'St-Louis, Gare de Saint-Louis': ['8718213', 'St-Louis, Gare de Saint-Louis', 'St-Louis, Gare'], //STL
	'Basel St. Johann': ['Basel St. Johann', 'Basel, Bahnhof St. Johann'],
	'Basel, Bahnhof St. Johann': ['Basel St. Johann', 'Basel, Bahnhof St. Johann'],
	'Olten, Leberngasse': ['Olten, Leberngasse', 'Olten, Schützenmatt'],
	'Olten, Schützenmatt': ['Olten, Leberngasse', 'Olten, Schützenmatt'],
	'Balsthal, Thalbrücke': ['Balsthal, Thalbrücke', 'Thalbrücke'],
	'Thalbrücke': ['Balsthal, Thalbrücke', 'Thalbrücke'],
	'Vignogn': ['Vignogn, vitg', 'Vignogn, Baselgia'],
	'Bern, Postautostation ': ['Bern, Hauptbahnhof'],
	'Fribourg/Freiburg': ['Fribourg/Freiburg', 'Fribourg/Freiburg, gare rout.', 'Fribourg/Freiburg, Pl. gare', 'Fribourg/Freiburg, Richemond/gare', 'Fribourg/Freiburg, gare/Tivoli', 'Fribourg/Freiburg, gare/Colisée'],
	'Fribourg/Freiburg, gare rout.': ['Fribourg/Freiburg', 'Fribourg/Freiburg, Pl. gare'],
	'Fribourg/Freiburg, Pl. gare': ['Fribourg/Freiburg', 'Fribourg/Freiburg, gare rout.'],
	'Lauterbrunnen (Seilbahn)': ['Lauterbrunnen', 'Lauterbrunnen, Bahnhof' , 'Lauterbrunnen (Seilbahn)'],
	'Lauterbrunnen, Bahnhof': ['Lauterbrunnen', 'Lauterbrunnen, Bahnhof' , 'Lauterbrunnen (Seilbahn)'],
	'Lauterbrunnen': ['Lauterbrunnen', 'Lauterbrunnen, Bahnhof' , 'Lauterbrunnen (Seilbahn)'],
	'Stechelberg, Schilthornbahn': ['Stechelberg, Schilthornbahn', 'Stechelberg (Schilthornbahn)'],
	'Stechelberg (Schilthornbahn)': ['Stechelberg, Schilthornbahn', 'Stechelberg (Schilthornbahn)'],
	'Grindelwald, Terminal': ['Grindelwald, Terminal', 'Grindelwald Terminal'],
	'Grindelwald Terminal': ['Grindelwald, Terminal', 'Grindelwald Terminal'],
	'Col-du-Pillon (téléphérique)': ['Col-du-Pillon (téléphérique)', 'Col-du-Pillon, Glacier 3000'],
	'Col-du-Pillon, Glacier 3000': ['Col-du-Pillon (téléphérique)', 'Col-du-Pillon, Glacier 3000'],
	'La Neuveville, poste': ['La Neuveville', 'La Neuveville, poste', 'La Neuveville (bateau)'],
	'La Neuveville': ['La Neuveville', 'La Neuveville, poste', 'La Neuveville (bateau)'],
	'La Neuveville (bateau)': ['La Neuveville', 'La Neuveville, poste', 'La Neuveville (bateau)'],
	'Ligerz, Bahnhof': ['Ligerz (Schiff)', 'Ligerz, Bahnhof', 'Ligerz (Talstation)'],
	'Ligerz (Schiff)': ['Ligerz (Schiff)', 'Ligerz, Bahnhof', 'Ligerz (Talstation)'],
	'Ligerz (Talstation)': ['Ligerz (Schiff)', 'Ligerz, Bahnhof', 'Ligerz (Talstation)'],
	'Tüscherz (Schiff)': ['Tüscherz, Dorfweg', 'Tüscherz (Schiff)'],
	'Tüscherz, Dorfweg': ['Tüscherz, Dorfweg', 'Tüscherz (Schiff)'],
	'Frinvillier, gare': ['Frinvillier, gare', 'Frinvillier-Taubenloch'],
	'Frinvillier-Taubenloch': ['Frinvillier, gare', 'Frinvillier-Taubenloch'],
	'Biel/Bienne Magglingenb.(Funi)': ['Biel/Bienne Magglingenb.(Funi)', 'Biel/Bienne, Magglingenbahn'],
	'Biel/Bienne, Magglingenbahn': ['Biel/Bienne Magglingenb.(Funi)', 'Biel/Bienne, Magglingenbahn'],
	'Biel/Bienne Leubringenb.(Funi)': ['Biel/Bienne Leubringenb.(Funi)', 'Biel/Bienne, Leubringenbahn'],
	'Biel/Bienne, Leubringenbahn': ['Biel/Bienne Leubringenb.(Funi)', 'Biel/Bienne, Leubringenbahn'],
	'Evilard, place du village': ['Evilard/Leubringen', 'Evilard, place du village'],
	'Evilard/Leubringen': ['Evilard/Leubringen', 'Evilard, place du village'],
	'Magglingen, Seilbahn': ['Magglingen/Macolin', 'Magglingen, Seilbahn'],
	'Magglingen/Macolin': ['Magglingen/Macolin', 'Magglingen, Seilbahn'],
	'Biel/Bienne': ['Biel/Bienne, Bahnhof/Gare', 'Biel/Bienne'],
	'Biel/Bienne, Bahnhof/Gare': ['Biel/Bienne, Bahnhof/Gare', 'Biel/Bienne'],
	'Biel/Bienne Bözingenfeld/Champ': ['Biel/Bienne, Bf Böz/gare Champ', 'Biel/Bienne Bözingenfeld/Champ'],
	'Biel/Bienne, Bf Böz/gare Champ': ['Biel/Bienne, Bf Böz/gare Champ', 'Biel/Bienne Bözingenfeld/Champ'],
	'Biel Mett': ['Biel/Bienne,Bf Mett/gare Mâche', 'Biel Mett'],
	'Biel/Bienne,Bf Mett/gare Mâche': ['Biel/Bienne,Bf Mett/gare Mâche', 'Biel Mett'],
	'Brig': ['Brig', 'Brig Bahnhofplatz', 'Brig, Bahnhof'],
	'Brig Bahnhofplatz': ['Brig', 'Brig Bahnhofplatz', 'Brig, Bahnhof'],
	'Iselle, stazione': ['Iselle, stazione', 'Iselle di Trasquera'],
	'Iselle di Trasquera': ['Iselle, stazione', 'Iselle di Trasquera'],

	
	'Samnaun-Ravaisch, Bergbahnen': ['Samnaun-Ravaisch, Bergbahnen', 'Samnaun-Ravaisch (Bergbahn)'],
	'Samnaun-Ravaisch (Bergbahn)': ['Samnaun-Ravaisch, Bergbahnen', 'Samnaun-Ravaisch (Bergbahn)'],
	'Scuol, Clozza': ['Scuol, Clozza', 'Scuol, Pütvia'],
	'Scuol, Pütvia': ['Scuol, Clozza', 'Scuol, Pütvia'],
	'Ftan Baraigla': ['Ftan Baraigla', 'Ftan, Baraigla'],
	'Ftan, Baraigla': ['Ftan Baraigla', 'Ftan, Baraigla'],
	'Ardez': ['Ardez', 'Ardez, staziun', 'Ardez, Bröl'],
	'Ardez, staziun': ['Ardez', 'Ardez, staziun', 'Ardez, Bröl'],
	'Ardez, Bröl': ['Ardez', 'Ardez, staziun', 'Ardez, Bröl'],
	'Lavin': ['Lavin', 'Lavin, staziun', 'Lavin, Plazza Gronda'],
	'Lavin, staziun': ['Lavin', 'Lavin, staziun', 'Lavin, Plazza Gronda'],
	'Lavin, Plazza Gronda': ['Lavin', 'Lavin, staziun', 'Lavin, Plazza Gronda'],
	'Susch': ['Susch', 'Susch, staziun', 'Susch, Plaz'],
	'Susch, staziun': ['Susch', 'Susch, staziun', 'Susch, Plaz'],
	'Susch, Plaz': ['Susch', 'Susch, staziun', 'Susch, Plaz'],
	'S-chanf Marathon': ['S-chanf Marathon', 'S-chanf, Zielgelände ESM'],
	'S-chanf, Zielgelände ESM': ['S-chanf Marathon', 'S-chanf, Zielgelände ESM'],
	'S-chanf': ['S-chanf', 'S-chanf, staziun', 'S-chanf, Chesa cumünela'],
	'S-chanf, Chesa cumünela': ['S-chanf', 'S-chanf, staziun', 'S-chanf, Chesa cumünela'],
	'Madulain': ['Madulain', 'Madulain, vih'],
	'Madulain, vih': ['Madulain', 'Madulain, vih'],
	'La Punt Chamues-ch': ['La Punt Chamues-ch', 'La Punt Chamues-ch, Bahnhof', 'La Punt Chamues-ch,Abzw Albula', 'La Punt, Krone'],
	'La Punt Chamues-ch, Bahnhof': ['La Punt Chamues-ch', 'La Punt Chamues-ch, Bahnhof', 'La Punt Chamues-ch,Abzw Albula', 'La Punt, Krone'],
	'La Punt Chamues-ch, Abzw Albula': ['La Punt Chamues-ch', 'La Punt Chamues-ch, Bahnhof', 'La Punt Chamues-ch,Abzw Albula', 'La Punt, Krone'],
	'La Punt, Krone': ['La Punt Chamues-ch', 'La Punt Chamues-ch, Bahnhof', 'La Punt Chamues-ch,Abzw Albula', 'La Punt, Krone'],
	'Samedan': ['Samedan', 'Samedan, Bahnhof', 'Samedan, Plazzet'],
	'Samedan, Bahnhof': ['Samedan', 'Samedan, Bahnhof', 'Samedan, Plazzet'],
	'Samedan, Plazzet': ['Samedan', 'Samedan, Bahnhof', 'Samedan, Plazzet'],
	'Celerina': ['Celerina', 'Celerina, Cresta Palace', 'Celerina, Punt Schlattain', 'Celerina, Centrum'],
	'Schlarigna': ['Celerina', 'Celerina, Cresta Palace', 'Celerina, Punt Schlattain', 'Celerina, Centrum'],
	'Celerina, Cresta Palace': ['Celerina', 'Celerina, Cresta Palace', 'Celerina, Punt Schlattain', 'Celerina, Centrum'],
	'Celerina, Punt Schlattain': ['Celerina', 'Celerina, Cresta Palace', 'Celerina, Punt Schlattain', 'Celerina, Centrum'],
	'Celerina, Centrum': ['Celerina', 'Celerina, Cresta Palace', 'Celerina, Punt Schlattain', 'Celerina, Centrum'],
	'St. Moritz, Schulhausplatz': ['St. Moritz, Schulhausplatz', 'St. Moritz (Standseilbahn)'],
	'St. Moritz (Standseilbahn)': ['St. Moritz, Schulhausplatz', 'St. Moritz (Standseilbahn)'],
	'St. Moritz Bad, Signalbahn': ['St. Moritz Bad, Signalbahn', 'St. Moritz Bad (Signalbahn)'],
	'St. Moritz Bad (Signalbahn)': ['St. Moritz Bad, Signalbahn', 'St. Moritz Bad (Signalbahn)'],
	'Surlej, Corvatschbahn': ['Surlej, Corvatschbahn', 'Silvaplana Surlej (Corvatsch)'],
	'Silvaplana Surlej (Corvatsch)': ['Surlej, Corvatschbahn', 'Silvaplana Surlej (Corvatsch)'],
	'Sils/Segl Maria,Furtschellasb.': ['Sils/Segl Maria,Furtschellasb.', 'Sils Maria (Furtschellasbahn)'],
	'Sils Maria (Furtschellasbahn)': ['Sils/Segl Maria,Furtschellasb.', 'Sils Maria (Furtschellasbahn)'],
	'Sils/Segl Maria, Posta': ['Sils/Segl Maria, Posta', 'Sils/Segl Maria Barchiröls'],
	'Sils/Segl Maria Barchiröls': ['Sils/Segl Maria, Posta', 'Sils/Segl Maria Barchiröls'],
	'Sils/Segl Baselgia,San Lurench': ['Sils/Segl Baselgia,San Lurench', 'Chastè'],
	'Chastè': ['Sils/Segl Baselgia,San Lurench', 'Chastè'],
	'Maloja, Capolago': ['Maloja, Capolago', 'Maloja (See)'],
	'Maloja (See)': ['Maloja, Capolago', 'Maloja (See)'],
	'Celerina Staz': ['Celerina Staz', 'Celerina, Buogl'],
	'Schlarigna Staz': ['Celerina Staz', 'Celerina, Buogl'],
	'Celerina, Buogl': ['Celerina Staz', 'Celerina, Buogl'],
	'Punt Muragl': ['Punt Muragl', 'Punt Muragl Staz', 'Punt Muragl, Talstation', 'Punt Muragl (Talstation)'],
	'Punt Muragl Staz': ['Punt Muragl', 'Punt Muragl Staz', 'Punt Muragl, Talstation', 'Punt Muragl (Talstation)'],
	'Punt Muragl, Talstation': ['Punt Muragl', 'Punt Muragl Staz', 'Punt Muragl, Talstation', 'Punt Muragl (Talstation)'],
	'Punt Muragl (Talstation)': ['Punt Muragl', 'Punt Muragl Staz', 'Punt Muragl, Talstation', 'Punt Muragl (Talstation)'],
	'Surovas': ['Pontresina, Post', 'Surovas'],
	'Pontresina, Post': ['Pontresina, Post', 'Surovas'],
	'Morteratsch': ['Morteratsch', 'Morteratsch, Abzweigung'],
	'Morteratsch, Abzweigung': ['Morteratsch', 'Morteratsch, Abzweigung'],
	'Bernina Diavolezza': ['Bernina Diavolezza', 'Bernina Diavolezza, Bahnhof', 'Bernina Diavolezza (Talstat.)'],
	'Bernina Diavolezza, Bahnhof': ['Bernina Diavolezza', 'Bernina Diavolezza, Bahnhof', 'Bernina Diavolezza (Talstat.)'],
	'Bernina Diavolezza (Talstat.)': ['Bernina Diavolezza', 'Bernina Diavolezza, Bahnhof', 'Bernina Diavolezza (Talstat.)'],
	'Bernina Lagalb': ['Bernina Lagalb', 'Bernina, Lagalbbahn', 'Curtinatsch'],
	'Bernina, Lagalbbahn': ['Bernina Lagalb', 'Bernina, Lagalbbahn', 'Curtinatsch'],
	'Curtinatsch': ['Bernina Lagalb', 'Bernina, Lagalbbahn', 'Curtinatsch'],
	'Ospizio Bernina': ['Ospizio Bernina', 'Ospizio Bernina, Albergo'],
	'Ospizio Bernina, Albergo': ['Ospizio Bernina', 'Ospizio Bernina, Albergo'],
	'Meschino': ['Miralago', 'Miralago, Stazione'],
	'Brusio': ['Brusio', 'Brusio, Posta'],
	'Brusio, Posta': ['Brusio', 'Brusio, Posta'],
	'Campascio': ['Campascio', 'Campascio, Strada'],
	'Campascio, Strada': ['Campascio', 'Campascio, Strada'],
	'Tirano': ['Tirano', 'Tirano, Stazione', 'Tirano FS'],
	'Tirano, Stazione': ['Tirano', 'Tirano, Stazione', 'Tirano FS'],
	'Tirano FS': ['Tirano', 'Tirano, Stazione', 'Tirano FS'],
    '8718206': ['8718206', '8753362'], //Mulhouse + Gare Centrale
    '8753362': ['8718206', '8753362'], //Mulhouse + Gare Centrale
	//das isch Kommentar
	'Baden': ['Baden', 'Baden, Bahnhof West', 'Baden, Bahnhof Ost', 'Baden, Postautostation'],
	'Baden, Bahnhof West': ['Baden', 'Baden, Bahnhof West', 'Baden, Bahnhof Ost', 'Baden, Postautostation'],
	'Baden, Bahnhof Ost': ['Baden', 'Baden, Bahnhof West', 'Baden, Bahnhof Ost', 'Baden, Postautostation'],
	'Baden, Postautostation': ['Baden', 'Baden, Bahnhof West', 'Baden, Bahnhof Ost', 'Baden, Postautostation'],
	'Brugg AG': ['Brugg AG', 'Brugg AG, Bahnhof/Campus', 'Brugg AG, Bahnhof/Zentrum'],
	'Brugg AG, Bahnhof/Zentrum': ['Brugg AG', 'Brugg AG, Bahnhof/Campus', 'Brugg AG, Bahnhof/Zentrum'],
	'Brugg AG, Bahnhof/Campus': ['Brugg AG', 'Brugg AG, Bahnhof/Campus', 'Brugg AG, Bahnhof/Zentrum'],
	'Le Locle': ['Le Locle', 'Le Locle, gare', 'Le Locle, gare/centre ville'],
	'Le Locle, gare': ['Le Locle', 'Le Locle, gare', 'Le Locle, gare/centre ville'],
	'Le Locle, gare/centre ville': ['Le Locle', 'Le Locle, gare', 'Le Locle, gare/centre ville'],
	'Rorschach, Hauptbahnhof Süd': ['Rorschach, Hauptbahnhof Süd', 'Rorschach', 'Rorschach, Bahnhofplatz'],
	'Rorschach': ['Rorschach, Hauptbahnhof Süd', 'Rorschach', 'Rorschach, Bahnhofplatz'],
	'Rorschach, Bahnhofplatz': ['Rorschach, Hauptbahnhof Süd', 'Rorschach', 'Rorschach, Bahnhofplatz'],
	'Rorschach Hafen (See)': ['Rorschach Hafen (See)', 'Rorschach, Signalstrasse', 'Rorschach, Rathaus', 'Rorschach Hafen'],
	'Rorschach, Signalstrasse': ['Rorschach Hafen (See)', 'Rorschach, Signalstrasse', 'Rorschach, Rathaus', 'Rorschach Hafen'],
	'Rorschach, Rathaus': ['Rorschach Hafen (See)', 'Rorschach, Signalstrasse', 'Rorschach, Rathaus', 'Rorschach Hafen'],
	'Rorschach Hafen': ['Rorschach Hafen (See)', 'Rorschach, Signalstrasse', 'Rorschach, Rathaus', 'Rorschach Hafen'],
	'Gümligen': ['Gümligen', 'Gümligen, Bahnhof (Bus)', 'Gümligen, Bahnhof (Tram)'],
	'Gümligen, Bahnhof (Bus)': ['Gümligen', 'Gümligen, Bahnhof (Bus)', 'Gümligen, Bahnhof (Tram)'],
	'Gümligen, Bahnhof (Tram)': ['Gümligen', 'Gümligen, Bahnhof (Bus)', 'Gümligen, Bahnhof (Tram)'],
	'Beatenbucht': ['Beatenbucht', 'Beatenbucht (See)'],
	'Beatenbucht (See)': ['Beatenbucht', 'Beatenbucht (See)'],
	'Merligen (See)': ['Merligen (See)', 'Merligen, Beatus'],
	'Merligen, Beatus': ['Merligen (See)', 'Merligen, Beatus'],
	'Gunten (See)': ['Gunten (See)', 'Gunten, Dorf'],
	'Gunten, Dorf': ['Gunten (See)', 'Gunten, Dorf'],
	'Oberhofen a. T., Dorf': ['Oberhofen a. T., Dorf', 'Oberhofen am Thunersee'],
	'Oberhofen am Thunersee': ['Oberhofen a. T., Dorf', 'Oberhofen am Thunersee'],
	'Hilterfingen, Post': ['Hilterfingen, Post', 'Hilterfingen (See)'],
	'Hilterfingen (See)': ['Hilterfingen, Post', 'Hilterfingen (See)'],
	'Spiez, Schiffstation': ['Spiez, Schiffstation', 'Spiez Schiffstation'],
	'Spiez Schiffstation': ['Spiez, Schiffstation', 'Spiez Schiffstation'],
	'Faulensee (See)': ['Faulensee (See)', 'Faulensee, Dorf'],
	'Faulensee, Dorf': ['Faulensee (See)', 'Faulensee, Dorf'],
	'Leissigen, Bahnhof': ['Leissigen (See)', 'Leissigen, Bahnhof'],
	'Leissigen (See)': ['Leissigen (See)', 'Leissigen, Bahnhof'],
	'Unterseen, Neuhaus': ['Unterseen, Neuhaus', 'Neuhaus (Unterseen) (See)'],
	'Neuhaus (Unterseen) (See)': ['Unterseen, Neuhaus', 'Neuhaus (Unterseen) (See)'],
	'Sundlauenen, Pilgerweg': ['Beatushöhlen-Sundlauenen', 'Sundlauenen, Pilgerweg'],
	'Beatushöhlen-Sundlauenen': ['Beatushöhlen-Sundlauenen', 'Sundlauenen, Pilgerweg'],
	'Dieni' : ['Dieni', 'Dieni, Pendicularas'],
	'Dieni, Pendicularas' : ['Dieni', 'Dieni, Pendicularas'],
	'Tschamut, Via Alpsu': ['Tschamut-Selva', 'Tschamut, Via Alpsu'],
	'Tschamut-Selva': ['Tschamut-Selva', 'Tschamut, Via Alpsu'],
	'Romanshorn Autoquai': ['Romanshorn Autoquai', 'Romanshorn', 'Romanshorn, Bahnhof', 'Romanshorn (See)'],
	'Romanshorn': ['Romanshorn Autoquai', 'Romanshorn', 'Romanshorn, Bahnhof', 'Romanshorn (See)'],
	'Romanshorn, Bahnhof': ['Romanshorn Autoquai', 'Romanshorn', 'Romanshorn, Bahnhof', 'Romanshorn (See)'],
	'Romanshorn (See)': ['Romanshorn Autoquai', 'Romanshorn', 'Romanshorn, Bahnhof', 'Romanshorn (See)'],
	'8029163': ['8029163', '8011121'], //Friedrichshafen-Hafen + Fähre
	'8011121': ['8029163', '8011121'], //Friedrichshafen-Hafen + Fähre
	'Genève': ['Genève', 'Genève, gare Cornavin'],
	'Genève, gare Cornavin': ['Genève', 'Genève, gare Cornavin'],
	'Bern, Brunnhof': ['Bern, Brunnhof', 'Bern Kaufmännischer Verband'],
	'Bern, Kaufmännischer Verband': ['Bern, Brunnhof', 'Bern Kaufmännischer Verband'],
	'Zug Schutzengel': ['Zug Schutzengel', 'Zug, Schutzengel'],
	'Zug, Schutzengel': ['Zug Schutzengel', 'Zug, Schutzengel'],
	'Zug, Chollermüli': ['Zug Chollermüli', 'Zug, Chollermüli', 'Zug, Rankhof'],
	'Zug Chollermüli': ['Zug Chollermüli', 'Zug, Chollermüli', 'Zug, Rankhof'],
	'Zug, Rankhof': ['Zug Chollermüli', 'Zug, Chollermüli', 'Zug, Rankhof'],
	'Cham Alpenblick': ['Cham Alpenblick', 'Cham, Eich'],
	'Cham, Eich': ['Cham Alpenblick', 'Cham, Eich'],
	'Hünenberg Zythus': ['Hünenberg Zythus', 'Hünenberg, Zythus'],
	'Hünenberg, Zythus': ['Hünenberg Zythus', 'Hünenberg, Zythus'],
	'Hünenberg Chämleten': ['Hünenberg Chämleten', 'Hünenberg, Badi Hünenberg'],
	'Hünenberg, Badi Hünenberg': ['Hünenberg Chämleten', 'Hünenberg, Badi Hünenberg'],
	'Zug, Landis & Gyr/Bahnhof': ['Zug', 'Zug, Landis & Gyr/Bahnhof'],
	'Zug, Bahnhof/Damm': ['Zug', 'Zug, Dammstrasse/Bahnhof', 'Zug, Bahnhofplatz', 'Zug, Dammstrasse/Bahnhof', 'Zug, Metalli/Bahnhof'],
	'Zug, Dammstrasse/Bahnhof': ['Zug', 'Zug, Dammstrasse/Bahnhof', 'Zug, Bahnhofplatz', 'Zug, Dammstrasse/Bahnhof', 'Zug, Metalli/Bahnhof'],
	'Zug, Bahnhofplatz': ['Zug', 'Zug, Dammstrasse/Bahnhof', 'Zug, Bahnhofplatz', 'Zug, Dammstrasse/Bahnhof', 'Zug, Metalli/Bahnhof'],
	'Zug, Metalli/Bahnhof': ['Zug', 'Zug, Dammstrasse/Bahnhof', 'Zug, Bahnhofplatz', 'Zug, Dammstrasse/Bahnhof', 'Zug, Metalli/Bahnhof'],
	'Zug': ['Zug', 'Zug, Dammstrasse/Bahnhof', 'Zug, Bahnhofplatz', 'Zug, Dammstrasse/Bahnhof', 'Zug, Metalli/Bahnhof', 'Zug, Landis & Gyr/Bahnhof'],
	'Zug Postplatz': ['Zug Postplatz', 'Zug, Postplatz'],
	'Zug, Postplatz': ['Zug Postplatz', 'Zug, Postplatz'],
	'Zug Fridbach': ['Zug Fridbach', 'Zug, Salesianum'],
	'Zug, Salesianum': ['Zug Fridbach', 'Zug, Salesianum'],
	'Zug Oberwil': ['Zug Oberwil', 'Oberwil b. Zug, Bahnhof'],
	'Oberwil b. Zug, Bahnhof': ['Zug Oberwil', 'Oberwil b. Zug, Bahnhof'],
	'Walchwil Hörndli': ['Walchwil Hörndli', 'Walchwil, Hörndlirain', 'Walchwil, Hörndli'],
	'Walchwil, Hörndlirain': ['Walchwil Hörndli', 'Walchwil, Hörndlirain'],
	'Walchwil, Hörndli': ['Walchwil Hörndli', 'Walchwil, Hörndli'],
	'Walchwil': ['Walchwil, Mütschi', 'Walchwil', 'Walchwil, Bahnhof'],
	'Walchwil, Bahnhof': ['Walchwil, Mütschi', 'Walchwil', 'Walchwil, Bahnhof'],
	'Walchwil, Mütschi': ['Walchwil, Mütschi', 'Walchwil', 'Walchwil, Bahnhof'],
	'Arth-Goldau': ['Arth-Goldau', 'Arth-Goldau RB', 'Arth-Goldau, Bahnhof'],
	'Arth-Goldau RB': ['Arth-Goldau', 'Arth-Goldau RB', 'Arth-Goldau, Bahnhof'],
	'Arth-Goldau, Bahnhof': ['Arth-Goldau', 'Arth-Goldau RB', 'Arth-Goldau, Bahnhof'],
	};
